#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Dec 14 16:38:01 2017

@author: oliverbeatson
"""

import tweepy
import datetime
import AccessKeys

# Uses keys from APP setup to access Twitter Account information
# Access Keys held in seperate folder

auth = tweepy.OAuthHandler(ConsumerKey, ConsumerSecret)
auth.set_access_token(AccessToken, AccessTokenSecret)

# Establishes API through tweepy
api = tweepy.API(auth)

# Iterate through all of the authenticated user's friends
for friend in tweepy.Cursor(api.friends).items(100):
    # Process the friend here
    print (friend)